#!/usr/bin/env bash
# Build a release tarball locally (same layout as .github/workflows/release-tarball.yml).
# Use for eb-setup tarball testing without pushing tags to GitHub.
#
# Usage:
#   ./scripts/build-test-tarballs.sh              # builds alpha.1 and alpha.2 pair
#   ./scripts/build-release-tarball.sh 1.0.0-alpha.1
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

VERSION="${1:-}"
OUT_DIR="${ROOT}/dist"

usage() {
    cat <<EOF
Usage: $(basename "$0") VERSION

Build dist/EGSnrc_CLRP-egs_brachy-VERSION.tar.gz (end-user, no .git).

Writes HEN_HOUSE/specs/release.mk into the tarball so compiles show EGS_RELEASE
and GIT_HASH even without .git in the install tree.

Examples:
  $(basename "$0") 1.0.0-alpha.1
  ./scripts/build-test-tarballs.sh   # alpha.1 + alpha.2 for install/update tests

Run from feature/eb-setup with submodules initialized:
  git submodule update --init --recursive
EOF
}

[[ -n "$VERSION" ]] || { usage; exit 1; }
[[ -f "$ROOT/eb-setup.sh" ]] || { echo "error: run from EGSnrc_CLRP repo root" >&2; exit 1; }
[[ -f "$ROOT/HEN_HOUSE/specs/unix.spec" ]] || { echo "error: HEN_HOUSE missing" >&2; exit 1; }
[[ -f "$ROOT/HEN_HOUSE/user_codes/egs_brachy/egs_brachy/Makefile" ]] || {
    echo "error: egs_brachy submodule not initialized (git submodule update --init --recursive)" >&2
    exit 1
}

DIR="EGSnrc_CLRP-egs_brachy-${VERSION}"
ARCHIVE="${OUT_DIR}/EGSnrc_CLRP-egs_brachy-${VERSION}.tar.gz"
STAGING="${OUT_DIR}/${DIR}"

GIT_HASH_VAL=""
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    GIT_HASH_VAL="$(git rev-parse --short=7 HEAD)"
fi

mkdir -p "$STAGING"
rsync -a \
    --exclude='.git/' \
    --exclude='.github/' \
    --exclude='.cursor/' \
    --exclude='dist/' \
    --exclude='egs_home/' \
    --exclude='eb-env.sh' \
    --exclude='HEN_HOUSE/lib/' \
    --exclude='HEN_HOUSE/bin/' \
    --exclude='HEN_HOUSE/log/' \
    --exclude='HEN_HOUSE/egs++/dso/' \
    ./ "${STAGING}/"

# Inject compile-time release metadata for tarball installs (no .git).
cat > "${STAGING}/HEN_HOUSE/specs/release.mk" <<EOF
# Generated by scripts/build-release-tarball.sh — do not edit.
EGS_RELEASE = -DEGS_RELEASE="\"${VERSION}\""
GIT_HASH = -DGIT_HASH="\"${GIT_HASH_VAL}\""
EOF

tar -czf "$ARCHIVE" -C "$OUT_DIR" "$DIR"
echo "Wrote $ARCHIVE"
echo "  $(du -h "$ARCHIVE" | cut -f1)  $(tar -tzf "$ARCHIVE" | wc -l | tr -d ' ') files"
if [[ -n "$GIT_HASH_VAL" ]]; then
    echo "  release.mk: EGS_RELEASE=${VERSION} GIT_HASH=${GIT_HASH_VAL}"
fi
